export { sampleLuminance } from './capture/luminance'
export { OwnedScreenCapture } from './capture/owner'
export type { CaptureBackend } from './capture/owner'
export type { CaptureSource, CurrentWorld, Metrics, Observation, ObservationFacts, PerceptionEventPort, ScreenCapturePort, ScreenFrame, VisionObservationPort } from './ports/contracts'
export { PrivacyGate } from './privacy/gate'
export type { ManualAuthorization, PrivacyDecision, PrivacyPolicy } from './privacy/gate'
export { PerceptionService } from './service'
export type { PerceptionOptions, PerceptionPorts } from './service'
export { VisionChain } from './vision/chain'
export type { VisionConfiguration } from './vision/chain'
export { OpenAiVisionAdapter } from './vision/openai-adapter'
export type { OpenAiVisionConfiguration } from './vision/openai-adapter'
