import type { IdleIntensity, VisualBehavior } from './contracts'

/** Native motion roles are opt-in semantic bindings. Unavailable motions use the bounded pose in the same entry. */
export const visualBehaviorCatalog: readonly VisualBehavior[] = [
  { id: 'gaze-drift', category: 'micro', durationMs: 4200, cooldownMs: 12000, weight: 2, lead: 'head', shape: 'drift', pose: { gazeX: 0.14, headYaw: 0.035, neckYaw: 0.012 }, gestures: [{ name: 'torso-turn', strength: 0.14 }], idle: true },
  { id: 'head-drift', category: 'micro', durationMs: 5200, cooldownMs: 16000, weight: 2, lead: 'head', shape: 'drift', pose: { headRoll: 0.04, headYaw: 0.028, neckRoll: 0.015, chestRoll: -0.013 }, gestures: [{ name: 'lean-side', strength: 0.25, delayMs: 170 }], idle: true },
  { id: 'breath-shift', category: 'micro', durationMs: 5200, cooldownMs: 25000, weight: 2, pose: { breath: 0.1, headPitch: 0.012 }, gestures: [{ name: 'chest-open', strength: 0.5 }, { name: 'shoulder-drop', strength: 0.55, delayMs: 260 }], idle: true },
  { id: 'posture-shift', category: 'short', durationMs: 5000, cooldownMs: 90000, weight: 1, shape: 'settle', pose: { headRoll: -0.035, chestYaw: 0.035 }, gestures: [{ name: 'lean-side' }, { name: 'asymmetric-arm-shift', delayMs: 220 }, { name: 'shoulder-drop', strength: 0.5, delayMs: 400 }], idle: true },
  { id: 'glance-left', category: 'short', durationMs: 2800, cooldownMs: 60000, weight: 3, lead: 'head', shape: 'quick', pose: { headYaw: 0.19, neckYaw: 0.05, gazeX: 0.30 }, gestures: [{ name: 'torso-turn', strength: 0.6 }, { name: 'asymmetric-arm-shift', strength: 0.3, delayMs: 130 }], idle: true },
  { id: 'glance-right', category: 'short', durationMs: 2800, cooldownMs: 60000, weight: 3, lead: 'head', shape: 'quick', pose: { headYaw: -0.19, neckYaw: -0.05, gazeX: -0.30 }, gestures: [{ name: 'torso-turn', strength: -0.6 }, { name: 'relaxed-drop', strength: 0.3, delayMs: 130 }], idle: true },
  { id: 'look-up', category: 'short', durationMs: 3000, cooldownMs: 65000, weight: 1, lead: 'head', pose: { headPitch: -0.105, neckPitch: -0.035, gazeY: 0.23 }, gestures: [{ name: 'chest-open', strength: 0.55 }, { name: 'open-arms-small', strength: 0.2, delayMs: 180 }], idle: true },
  { id: 'look-down', category: 'short', durationMs: 3000, cooldownMs: 65000, weight: 1, lead: 'head', pose: { headPitch: 0.115, neckPitch: 0.04, gazeY: -0.23 }, gestures: [{ name: 'chest-collapse', strength: 0.5 }, { name: 'hands-inward', strength: 0.22, delayMs: 180 }], idle: true },
  { id: 'head-tilt', category: 'short', durationMs: 3500, cooldownMs: 70000, weight: 2, lead: 'head', pose: { headRoll: 0.115, neckRoll: 0.025, leftShoulderRoll: 0.047, rightShoulderRoll: 0.015 }, gestures: [{ name: 'lean-side', strength: -0.5 }, { name: 'asymmetric-arm-shift', strength: 0.4 }], idle: true },
  { id: 'tiny-smile', category: 'short', durationMs: 3000, cooldownMs: 150000, weight: 0.25, pose: { headPitch: -0.025, headRoll: -0.018 }, gestures: [{ name: 'chest-open', strength: 0.32 }, { name: 'open-arms-small', strength: 0.16, delayMs: 140 }], expression: 'happy', expressionWeight: 0.14, idle: true },
  { id: 'curious', category: 'short', durationMs: 4000, cooldownMs: 30000, weight: 1, lead: 'head', pose: { headRoll: 0.14, headPitch: -0.035, neckRoll: 0.03, headYaw: 0.045 }, gestures: [{ name: 'lean-forward', strength: 1.1 }, { name: 'small-shrug', strength: 0.65 }, { name: 'thoughtful-hand', strength: 0.36, delayMs: 250 }] },
  { id: 'fidget', category: 'short', durationMs: 4800, cooldownMs: 100000, weight: 0.4, shape: 'fidget', gestures: [{ name: 'subtle-hand-fidget' }, { name: 'asymmetric-arm-shift', strength: 0.7, delayMs: 180 }, { name: 'lean-side', strength: 0.35, shape: 'settle' }], idle: true },
  { id: 'attentive', category: 'listening', durationMs: 3600, cooldownMs: 6000, weight: 1, shape: 'quick', pose: { headPitch: 0.025, headYaw: -0.015 }, gestures: [{ name: 'attentive-posture', strength: 1.3 }, { name: 'open-arms-small', strength: 0.18, delayMs: 140 }] },
  { id: 'listening', category: 'listening', durationMs: 5600, cooldownMs: 6000, weight: 1, pose: { headPitch: 0.035, headRoll: 0.065, neckRoll: 0.023 }, gestures: [{ name: 'lean-forward', strength: 1.25 }, { name: 'shoulder-drop', strength: 0.65 }, { name: 'asymmetric-arm-shift', strength: 0.65 }, { name: 'subtle-hand-fidget', strength: 0.4, shape: 'settle', delayMs: 900 }] },
  { id: 'nod', category: 'listening', durationMs: 1800, cooldownMs: 20000, weight: 1, lead: 'head', shape: 'nod', pose: { headPitch: 0.14, neckPitch: 0.045, chestPitch: 0.022, bodyPitch: 0.013 }, gestures: [{ name: 'shoulder-drop', strength: 0.25 }] },
  { id: 'stretch', category: 'long', durationMs: 8000, cooldownMs: 300000, weight: 0.5, shape: 'stretch', motionRole: 'stretch', pose: { headPitch: -0.075, neckPitch: -0.03, headRoll: -0.028 }, gestures: [{ name: 'stretch-open' }, { name: 'lean-side', strength: 0.38, delayMs: 500 }], idle: true },
  { id: 'relaxed', category: 'long', durationMs: 6500, cooldownMs: 200000, weight: 2, pose: { headRoll: -0.06, headPitch: 0.035 }, gestures: [{ name: 'shoulder-drop', strength: 1.15 }, { name: 'relaxed-drop', strength: 1.1 }, { name: 'lean-back', strength: 0.3 }], expression: 'relaxed', expressionWeight: 0.22, idle: true },
  { id: 'sleepy', category: 'long', durationMs: 6500, cooldownMs: 300000, weight: 0.3, motionRole: 'yawn', pose: { headPitch: 0.13, headRoll: 0.055 }, gestures: [{ name: 'chest-collapse', strength: 0.85 }, { name: 'shoulder-drop' }, { name: 'relaxed-drop', strength: 0.75, delayMs: 400 }], expression: 'sleepy', expressionWeight: 0.2, idle: true },
  { id: 'look-around', category: 'long', durationMs: 7500, cooldownMs: 180000, weight: 2, lead: 'head', shape: 'scan', pose: { headYaw: 0.26, neckYaw: 0.055, gazeX: 0.27 }, gestures: [{ name: 'torso-turn', strength: 1.15 }, { name: 'asymmetric-arm-shift', strength: 0.45, delayMs: 300 }], idle: true },
  { id: 'thoughtful', category: 'long', durationMs: 6500, cooldownMs: 200000, weight: 1, pose: { headYaw: 0.12, headPitch: -0.055, headRoll: -0.075 }, gestures: [{ name: 'torso-turn', strength: -0.5 }, { name: 'lean-side', strength: -0.55 }, { name: 'thoughtful-hand', strength: 0.65, delayMs: 280 }], idle: true },
  { id: 'restless', category: 'long', durationMs: 6500, cooldownMs: 300000, weight: 0.25, shape: 'fidget', pose: { headYaw: 0.08, neckRoll: -0.025 }, gestures: [{ name: 'lean-side', strength: 1.2 }, { name: 'torso-turn', strength: -0.7, delayMs: 350 }, { name: 'subtle-hand-fidget', strength: 1.2, delayMs: 220 }, { name: 'asymmetric-arm-shift', strength: 1.2, delayMs: 470 }], idle: true },
  { id: 'settle', category: 'long', durationMs: 5000, cooldownMs: 150000, weight: 1, shape: 'settle', pose: { headPitch: 0.035, headRoll: -0.02 }, gestures: [{ name: 'shoulder-drop' }, { name: 'relaxed-drop', strength: 0.85, delayMs: 150 }, { name: 'lean-side', strength: -0.35, delayMs: 600 }], idle: true },
  { id: 'thinking', category: 'waiting', durationMs: 6000, cooldownMs: 12000, weight: 1, pose: { headYaw: 0.16, headPitch: -0.085, headRoll: 0.06, neckYaw: 0.035, gazeX: 0.16, gazeY: 0.12 }, gestures: [{ name: 'torso-turn', strength: -0.85 }, { name: 'thoughtful-hand', strength: 1.1, delayMs: 240 }, { name: 'chest-collapse', strength: 0.35 }] },
  { id: 'waiting', category: 'waiting', durationMs: 5000, cooldownMs: 15000, weight: 1, shape: 'drift', pose: { headYaw: -0.07 }, gestures: [{ name: 'lean-side', strength: 0.65 }, { name: 'asymmetric-arm-shift', strength: 0.45, shape: 'settle', delayMs: 650 }, { name: 'shoulder-drop', strength: 0.4 }] },
  { id: 'happy', category: 'positive', durationMs: 3600, cooldownMs: 12000, weight: 1, shape: 'quick', pose: { headRoll: -0.07, headPitch: -0.055, neckRoll: 0.022 }, gestures: [{ name: 'chest-open' }, { name: 'open-arms-small' }, { name: 'excited-lift', strength: 0.7, delayMs: 120 }], expression: 'happy', expressionWeight: 0.35 },
  { id: 'amused', category: 'positive', durationMs: 3400, cooldownMs: 12000, weight: 1, shape: 'quick', pose: { headPitch: 0.055, headRoll: -0.08, headYaw: -0.08 }, gestures: [{ name: 'lean-back', strength: 0.8, shape: 'nod' }, { name: 'shoulder-lift', strength: 0.7, shape: 'nod', delayMs: 80 }, { name: 'hands-inward', strength: 0.65, delayMs: 180 }, { name: 'chest-open', strength: 0.45 }], expression: 'happy', expressionWeight: 0.28 },
  { id: 'concerned', category: 'concerned', durationMs: 4200, cooldownMs: 15000, weight: 1, pose: { headRoll: 0.085, headPitch: 0.065, neckRoll: 0.025 }, gestures: [{ name: 'lean-forward' }, { name: 'concerned-fold' }, { name: 'chest-collapse', strength: 0.45 }], expression: 'sad', expressionWeight: 0.28 },
  { id: 'frown', category: 'concerned', durationMs: 3400, cooldownMs: 15000, weight: 1, shape: 'quick', pose: { headPitch: 0.09, neckPitch: 0.028, chestYaw: -0.035 }, gestures: [{ name: 'chest-collapse', strength: 0.55 }, { name: 'shoulder-lift', strength: 0.36 }, { name: 'hands-inward', strength: 0.55 }], expression: 'angry', expressionWeight: 0.26 },
  { id: 'surprised', category: 'surprise', durationMs: 1800, cooldownMs: 15000, weight: 1, shape: 'reaction', pose: { headPitch: -0.115, headYaw: -0.035 }, gestures: [{ name: 'recoil' }, { name: 'shoulder-lift', strength: 1.2 }], expression: 'surprised', expressionWeight: 0.36 },
  { id: 'focused', category: 'watching', durationMs: 5000, cooldownMs: 15000, weight: 1, pose: { headPitch: 0.035, headYaw: 0.005 }, gestures: [{ name: 'attentive-posture', strength: 0.85 }, { name: 'lean-forward', strength: 0.9 }, { name: 'hands-inward', strength: 0.2 }] },
]

/** These are visual settings. They do not encode or infer mood. Intervals use milliseconds. */
export const idleProfiles: Readonly<Record<IdleIntensity, { interval: readonly [number, number], amplitude: number, longProbability: number, neutralMs: number }>> = {
  still: { interval: [Infinity, Infinity], amplitude: 0, longProbability: 0, neutralMs: 15000 },
  calm: { interval: [50000, 100000], amplitude: 0.35, longProbability: 0.025, neutralMs: 16000 },
  normal: { interval: [25000, 65000], amplitude: 0.55, longProbability: 0.06, neutralMs: 12000 },
  lively: { interval: [15000, 40000], amplitude: 0.75, longProbability: 0.1, neutralMs: 9000 },
}
